Announce KubeDB v2022.05.24
appscode/blog pull request #141
Opened 2022-05-20 11:20 UTC by kamolhasan

Signed-off-by: kamolhasan <kamol@appscode.com>

2022-05-20 11:30 UTC, raihankhan commented on content/post/kubedb-v2022.05.24/index.md
> +In this release, we are expanding our support for dashboards. Now KubeDB supports `opensearch-dashboard` with ElasticsearchVersion CRO `opensearch-1.1.0`, `opensearch-1.2.0`, and `opensearch-1.3.2`.
Typo -> OpenSearch Dashboards

2022-05-20 11:33 UTC, rakibulhossain requested changes

2022-05-20 11:33 UTC, rakibulhossain commented on content/post/kubedb-v2022.05.24/index.md
> +We are pleased to announce the release of [KubeDB v2022.05.24](https://kubedb.com/docs/v2022.05.24/setup/). This post lists all the major changes done in this release since the last release. This rel
"Redesigned Redis"

2022-05-20 11:33 UTC, rakibulhossain commented on content/post/kubedb-v2022.05.24/index.md
> +In the `spec.topology` you refer to `SemiSync` Mode and in the `spec.topolgy.semiSync` you can refer to how many replicas, the source will wait for an acknowledgment before committing, how long the s
`spec.topolgy.semiSync` -> `spec.topology.semiSync`

2022-05-20 11:37 UTC, raihankhan requested changes

2022-05-20 11:37 UTC, raihankhan commented on content/post/kubedb-v2022.05.24/index.md
> +In this release, We are happy to introduce the support for `Elasticsearch V8`. Now, you can provision and manage Elasticsearch V8 with KubeDB. New supported ElasticsearchVersion CROs are `xpack-8.2.0
The `kubedb-xpack-8.2.0` is packed with  `elasticsearch:8.2.0` with pre-installed plugins: `repository-s3`, `repository-azure`, `repository-hdfs`, and `repository-gcs`.

2022-05-20 11:37 UTC, raihankhan commented on content/post/kubedb-v2022.05.24/index.md
> +In this release, we are expanding our support for dashboards. Now KubeDB supports `opensearch-dashboard` with ElasticsearchVersion CRO `opensearch-1.1.0`, `opensearch-1.2.0`, and `opensearch-1.3.2`.
Typo: `opensearch-dashboard` > `OpenSearch Dashboards`

2022-05-20 11:41 UTC, ArnobKumarSaha submitted a review, later dismissed

2022-05-20 11:44 UTC, raihankhan submitted a review, later dismissed
LGTM!

2022-05-20 11:50 UTC, TasdidurRahman approved these changes
LGTM

2022-05-20 11:58 UTC, Shaad7 reviewed
LGTM

2022-05-20 11:58 UTC, Shaad7 approved these changes

2022-05-20 12:02 UTC, rakibulhossain approved these changes

2022-05-20 12:03 UTC, rakibulhossain submitted a review, later dismissed
LGTM!

2022-05-23 03:46 UTC, spectro30 submitted a review, later dismissed
LGTM

2022-05-23 04:08 UTC, Emon46 submitted a review, later dismissed
LGTM!

2022-05-24 08:46 UTC, Emon46 approved these changes
LGTM!

2022-05-24 08:48 UTC, merged