Elasticsearch aws
appscode/blog pull request #185
Opened 2022-08-29 05:47 UTC by DRoyyy

2022-08-29 11:11 UTC, raihankhan requested changes

2022-08-29 11:11 UTC, raihankhan commented on content/post/run-elasticsearch-in-aws/index.md
> +In this section, we are going to create few indexes in Elasticsearch. At first, we are going to port-forward the respective Service so that we can connect with the database from our local machine. Th
On the deployment of Elasticsearch yaml, the operator creates a governing service that is named after the Elasticsearch object name itself. We are going to use this object to....

2022-08-29 11:11 UTC, raihankhan commented on content/post/run-elasticsearch-in-aws/index.md
> +Now, let’s verify that the index have been created successfully.
has been

2022-08-29 11:11 UTC, raihankhan commented on content/post/run-elasticsearch-in-aws/index.md
> +We have made an in depth video on Elasticsearch Hot-Warm-Cold Architecture Management with Kibana in Kubernetes Using KubeDB. You can have a look into the video below:
We have an in-depth walkthrough on...

2022-08-29 12:28 UTC, raihankhan approved these changes
LGTM!

2022-08-30 05:34 UTC, kamolhasan approved these changes

2022-08-30 05:36 UTC, merged