Add different ui rendering methods blog
appscode/blog pull request #290
Opened 2023-05-19 11:36 UTC by nurRiyad

2023-05-19 11:49 UTC, s4k1b requested changes

2023-05-19 11:49 UTC, s4k1b commented on content/post/different-ui-rendering-methods/index.md
> +  - selfhost.byte.builders
add csr, ssr, ssg, ur, spa

2023-05-19 11:49 UTC, s4k1b commented on content/post/different-ui-rendering-methods/index.md
> +  - selfhost.byte.builders
not needed

2023-05-19 11:49 UTC, s4k1b commented on content/post/different-ui-rendering-methods/index.md
> +In universal rendering when the browser requests a URL with universal (server-side + client-side) rendering enabled, the server returns a fully rendered HTML page to the browser. Whether the page has
"the browser runs the JavaScript code in a server environment"

what?

2023-05-19 11:49 UTC, s4k1b commented on content/post/different-ui-rendering-methods/index.md
> +Universal rendering allows a Nuxt application to provide quick page load times while preserving the benefits of client-side rendering. Furthermore, as the content is already present in the HTML docum
don't need to mention Nuxt here

2023-05-19 11:49 UTC, s4k1b commented on content/post/different-ui-rendering-methods/index.md
> +We have several web project to render. Some of them require high interactivity, some of then need SEO and others are content heavy. Depends on the project requirement to use different rendering metho
Change the first sentence to "Here at Appscode, we have developed several web applications that utilize the different rendering techniques mentioned here."

2023-05-22 12:13 UTC, DRoyyy submitted a review, later dismissed

2023-05-23 04:37 UTC, s4k1b approved these changes

2023-05-23 04:47 UTC, s4k1b approved these changes

2023-05-23 04:48 UTC, DRoyyy approved these changes

2023-05-23 23:32 UTC, merged