Add KubeStash v2023.12.28 release note
appscode/blog pull request #378
Opened 2024-01-04 06:52 UTC by ishtiaqhimel

2024-01-04 06:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/appscode/blog?pullRequest=378) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/appscode/blog?pullRequest=378) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/appscode/blog?pullRequest=378) it.</sub>

2024-01-04 13:04 UTC, hmsayem commented on content/post/kubestash-v2023.12.28/index.md
> +- Fixed a bug in validation for selector type usage policy.
- Fixed a bug that was preventing the creation of multiple Retention Policies when a default one exists in a namespace.

2024-01-04 13:09 UTC, hmsayem commented on content/post/kubestash-v2023.12.28/index.md
> +- Resolved addon version for MySQL `8.1.0` and `8.2.0`.
- Fixed a bug that was causing an "addon not found" error for MySQL versions ` 8.1.0` and `8.2.0`.

2024-01-05 05:15 UTC, anisurrahman75 submitted a review, later dismissed

2024-01-05 09:27 UTC, hmsayem requested changes

2024-01-05 09:27 UTC, hmsayem commented on content/post/kubestash-v2023.12.28/index.md
> +### Improvements & Bug fixes
mprovements & Bug fixes > Bug Fixes

2024-01-05 09:31 UTC, hmsayem approved these changes

2024-01-05 09:33 UTC, DRoyyy approved these changes

2024-01-05 09:33 UTC, merged