Add comparison between stash and stash 2.0
appscode/blog pull request #418
Opened 2024-04-09 09:39 UTC by ishtiaqhimel

2024-04-09 11:35 UTC, hmsayem requested changes

2024-04-09 11:35 UTC, hmsayem commented on content/post/comparing-stash-and-kubestash/index.md
> +- In KubeStash, we've introduced a new CRD named [RetentionPolicy](https://kubestash.com/docs/v2024.3.16/concepts/crds/retentionpolicy/) which specifies how the old Snapshots should be cleaned up. Th
In KubeStash, we've introduced a new CRD named RetentionPolicy that allows you to set how long you’d like to retain the backup data. It offers more control over snapshot cleanup policies compared to Stash. It is also reusable across namespaces. In contrast, in Stash, you need to provide the retention policy separately in every BackupConfiguration.

2024-04-09 11:35 UTC, hmsayem commented on content/post/comparing-stash-and-kubestash/index.md
> +- In KubeStash, we've introduced a new CRD named [HookTemplate](https://kubestash.com/docs/v2024.3.16/concepts/crds/hooktemplate/) which basically specifies a template for an action that will be exec
In KubeStash, we've introduced a new CRD named which specifies a template for an action that will be executed before or/and after backup/restore process. It provides better control over the backup process by letting you use custom variable in the BackupBlueprint. It is also reusable across namespaces. In contrast, in Stash, you need to specify the hook separately in every BackupConfiguration/RestoreSession.

2024-04-09 11:35 UTC, hmsayem commented on content/post/comparing-stash-and-kubestash/index.md
> +- Implement new addons according to the users requirements
add some details.

2024-04-18 08:47 UTC, hmsayem requested changes

2024-04-18 08:47 UTC, hmsayem commented on content/post/comparing-stash-and-kubestash/index.md
> +These are some key features that have been improved or added in KubeStash. Additionally, there are numerous other features that have been enhanced or incorporated into KubeStash. To learn more visit
While the above highlights some of the key features and improvements of KubeStash, explore the KubeStash [documentation](https://kubestash.com/docs/v2024.3.16/welcome/) for a comprehensive view of all the new features.

2024-04-18 10:04 UTC, anisurrahman75 approved these changes

2024-09-27 11:24 UTC, ArnobKumarSaha submitted a review, later dismissed

2024-12-30 12:22 UTC, merged