Add Release notes for KubeDB v2024.9.30
appscode/blog pull request #470
Opened 2024-09-27 10:18 UTC by AshrafulHaqueToni

2024-09-27 10:32 UTC, tapojit047 requested changes

2024-09-27 10:32 UTC, tapojit047 commented on content/post/kubedb-v2024.9.30/index.md
> +BackupStorage: refers to a cloud storage backend (like `s3`, `gcs` etc.) you prefer.
Make BackupStorage, RetentionPolicy, Secrets, BackupConfiguration, RestoreSession **bold**

2024-09-27 10:32 UTC, tapojit047 commented on content/post/kubedb-v2024.9.30/index.md
> +RestoreSession: specifies the target database, addon, datasource to use to restore the backed up data. Here is an example of BackupConfiguration
Remove "Here is an example of BackupConfiguration"

2024-09-27 10:42 UTC, sheikh-arman requested changes
Change the `Internally Managed ClickHouse Keeper` heading
to `Managed ClickHouse Keeper`

2024-09-27 10:54 UTC, ishtiaqhimel requested changes

2024-09-27 10:54 UTC, ishtiaqhimel commented on content/post/kubedb-v2024.9.30/index.md
> +    restoreNamespace: dev
`restoreNamespace` should be the sub-field of `singlestore`.
```
singlestore:
  restoreNamespace: dev
```

Also do not need to specify `db: true`. Its default value is true.

2024-10-01 04:53 UTC, obaydullahmhs requested changes

2024-10-01 04:53 UTC, obaydullahmhs commented on content/post/kubedb-v2024.9.30/index.md
> +- **New Version Support**: Added support for MySQL version 8.4.2 and Microsoft SQL Server 2022-cu14.
highlight versions

2024-10-01 04:53 UTC, obaydullahmhs commented on content/post/kubedb-v2024.9.30/index.md
> +Supported Versions: 4.1.6 & 5.0.0
highlight versions

2024-10-01 04:53 UTC, obaydullahmhs commented on content/post/kubedb-v2024.9.30/index.md
> +You need to set spec.clusterTopology.clickHouseKeeper.externallyManaged field as false to use KubeDB managed clickhouse keeper.
highlight `spec.clusterTopology.clickHouseKeeper.externallyManaged`

2024-10-01 04:53 UTC, obaydullahmhs commented on content/post/kubedb-v2024.9.30/index.md
> +kind: BackupConfiguration
use ```yaml. also update all if missing

2024-10-01 04:53 UTC, obaydullahmhs commented on content/post/kubedb-v2024.9.30/index.md
> +- **Network Policies**: We have added support for [NetworkPolicy](https://kubernetes.io/docs/concepts/services-networking/network-policies/) in the release.Now Users can pass
need a space before `Now Users`

2024-10-01 10:51 UTC, mohin7 commented on content/post/kubedb-v2024.9.30/index.md
> +- Ashraful Haque Tani
Update with `Ashraful Haque`

2024-10-02 02:48 UTC, merged