Add release note for kubestash v2024.9.30
appscode/blog pull request #472
Opened 2024-09-27 11:55 UTC by ishtiaqhimel

2024-09-27 13:31 UTC, hmsayem requested changes

2024-09-27 13:31 UTC, hmsayem commented on content/post/kubestash-v2024.9.30/index.md
> +### Handle Content-Type YAML while Uploading to Object Storage
```suggestion
#### Content-Type Handling for YAML Uploads to Object Storage
```

2024-09-27 13:31 UTC, hmsayem commented on content/post/kubestash-v2024.9.30/index.md
> +#### Handle Unexpected failures for Backup Or Restore Containers
```suggestion
#### Handling Unexpected failures for Backup Or Restore

2024-09-27 13:31 UTC, hmsayem commented on content/post/kubestash-v2024.9.30/index.md
> +
```suggestion
KubeStash will now wrap the backup and restore commands with these timeouts, ensuring that Snapshot and RestoreSession statuses are updated with a 'deadline exceeded' error message.
```

2024-09-27 14:07 UTC, hmsayem requested changes

2024-09-27 14:07 UTC, hmsayem commented on content/post/kubestash-v2024.9.30/index.md
> +Similarly, the `spec.timeout` field has been removed from `RestoreSession` and replaced with `spec.restoreTimeout`. This defines how long KubeStash should wait for a restore to complete before markin
```suggestion
We’ve updated the declarative API for `BackupConfiguration` and `RestoreSession` in KubeStash. The `spec.sessions[*].timeout` field has been removed from `BackupConfiguration` and replaced with `spec.sessions[*].backupTimeout`, which sets the maximum duration for the backup. KubeStash wraps the backup command(s) with this timeout. If the backup doesn’t finish within this time, the Snapshot and BackupSession should be marked as `Failed`. By default, no backup timeout is set.

Similarly, the `spec.timeout` field has been removed from `RestoreSession` and replaced with `spec.restoreTimeout` which sets the maximum duration for the restore. KubeStash wraps the restore command(s) with this timeout.  If the restore doesn’t finish within this time, the RestoreSession should be marked as `Failed`. By default, no restore timeout is set.
```

2024-09-27 14:07 UTC, hmsayem commented on content/post/kubestash-v2024.9.30/index.md
> +We’ve fixed a bug where the backup/restore job could remain active even after the deadline was exceeded (based on the timeout) with the `BackupSession` marked as failed. Now, KubeStash will wrap time
```suggestion
```

2024-09-30 07:00 UTC, hmsayem commented
LGTM

2024-09-30 07:06 UTC, anisurrahman75 approved these changes

2024-09-30 07:08 UTC, hmsayem approved these changes

2024-09-30 07:08 UTC, merged