Add Release notes for KubeDB v2024.11.18
appscode/blog pull request #479
Opened 2024-11-19 12:44 UTC by tapojit047

2024-11-21 04:22 UTC, Evanraisul submitted a review, later dismissed
LGTM

2024-11-21 04:54 UTC, obaydullahmhs requested changes

2024-11-21 04:54 UTC, obaydullahmhs commented on content/post/kubedb-v2024.11.18/index.md
> +![Cassandra Summary Dashboard](cassandra-summery.png)
rename to `cassandra-summary` ?

2024-11-21 04:54 UTC, obaydullahmhs commented on content/post/kubedb-v2024.11.18/index.md
> +- **Rotate Auth**: A new Ops Request named `RotateAuth` has been introduced. This feature enables users to rotate the credentials of the database enhancing overall security. It is initially added for
also added for elasticsearch

2024-11-21 04:54 UTC, obaydullahmhs commented on content/post/kubedb-v2024.11.18/index.md
> +```
```yaml

2024-11-21 05:06 UTC, obaydullahmhs requested changes

2024-11-21 05:06 UTC, obaydullahmhs commented on content/post/kubedb-v2024.11.18/index.md
> +If the secret is referenced, the operator will update the .spec.authSecret.name` with the new secret name. Here is the yaml,
missed a backtick here. .spec.authSecret.name`

2024-11-21 09:15 UTC, HiranmoyChowdhury submitted a review, later dismissed
LGTM!

2024-11-21 09:27 UTC, sayedppqq approved these changes
LGTM!

2024-11-21 11:21 UTC, Neaj-Morshad-101 approved these changes
LGTM!

2024-11-21 11:34 UTC, Neaj-Morshad-101 requested changes

2024-11-21 11:34 UTC, Neaj-Morshad-101 commented on content/post/kubedb-v2024.11.18/index.md
> +  - The field `spec.leaderElection` is now moved under `spec.topology.availabilityGroup.leaderElection`.
Leader Election Configuration: The field `spec.leaderElection` has been moved to `spec.topology.availabilityGroup.leaderElection`.

2024-11-21 11:34 UTC, Neaj-Morshad-101 commented on content/post/kubedb-v2024.11.18/index.md
> +          - kubedb
We can remove this part.

2024-11-21 11:34 UTC, Neaj-Morshad-101 commented on content/post/kubedb-v2024.11.18/index.md
> +- For leader election, adjust parameters under `spec.topology.availabilityGroup.leaderElection` as needed.
> Note: Use `spec.tls` to configure all TLS/SSL-related settings, including endpoint authentication for Availability Group replicas.

Remove it:
- For leader election, adjust parameters under `spec.topology.availabilityGroup.leaderElection` as needed.

2024-11-21 11:34 UTC, Neaj-Morshad-101 commented on content/post/kubedb-v2024.11.18/index.md
> +For a complete list of environment variables and their usage, refer to the [official Microsoft documentation](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variab
To know more about these environment variables and their usage,

2024-11-21 11:49 UTC, Neaj-Morshad-101 submitted a review, later dismissed

2024-11-21 12:12 UTC, pritamdas99 submitted a review, later dismissed
LGTM!

2024-11-21 12:49 UTC, raihankhan approved these changes
LGTM 👍🏻

2024-11-22 04:17 UTC, souravbiswassanto submitted a review, later dismissed

2024-11-22 05:49 UTC, ArnobKumarSaha submitted a review, later dismissed

2024-11-22 09:22 UTC, merged