Add release note for kubedb-2024.12.19
appscode/blog pull request #485
Opened 2024-12-19 05:08 UTC by pritamdas99

2024-12-19 11:23 UTC, tapojit047 reviewed
The order of the the databases should be sorted alphabetically.

2024-12-19 12:36 UTC, ArnobKumarSaha requested changes
Lets make it 2024.12.18

2024-12-20 06:48 UTC, tapojit047 requested changes

2024-12-20 06:48 UTC, tapojit047 commented on content/post/kubedb-v2024.12.18/index.md
> +- **New Version Support**: New versions have been added for `Elasticsearch`, `MySQL`, `Redis`, `Solr`, `Singlestore`.
`Druid` is missing

2024-12-20 06:51 UTC, tapojit047 requested changes

2024-12-20 06:51 UTC, tapojit047 commented on content/post/kubedb-v2024.12.18/index.md
> +## MSSQLSERVER
This should be lowercase

2024-12-20 06:51 UTC, pritamdas99 commented on content/post/kubedb-v2024.12.18/index.md
> +- **New Version Support**: New versions have been added for `Elasticsearch`, `MySQL`, `Redis`, `Solr`, `Singlestore`.
added

2024-12-20 09:21 UTC, Neaj-Morshad-101 requested changes

2024-12-20 09:21 UTC, Neaj-Morshad-101 commented on content/post/kubedb-v2024.12.18/index.md
> +KubeDB **v2024.12.19** is now available! This latest release brings significant performance enhancements, improved reliability, and new features to database management experience on Kubernetes. Here
v2024.12.18

2024-12-20 09:21 UTC, Neaj-Morshad-101 commented on content/post/kubedb-v2024.12.18/index.md
> +- **New Version Support**: New versions have been added for `Druid`, `Elasticsearch`, `FerretDB`, `Kafka`, `MariaDB`, `Memcached`, `MSSQLServer`, `MySQL`, `RabbitMQ`, `Redis`, `Solr`, `Singlestore`.
`MSSQLServer` -> `Microsoft SQL Server`

2024-12-20 09:21 UTC, Neaj-Morshad-101 commented on content/post/kubedb-v2024.12.18/index.md
> +- **OpsRequest Support**: New `OpsRequest` features have been added for `Memcached`, `MySQL`, offering greater flexibility for managing database administrative tasks. Moreover, a new `OpsRequest` fea
Include Microsoft SQL Server

2024-12-20 09:21 UTC, Neaj-Morshad-101 commented on content/post/kubedb-v2024.12.18/index.md
> +- **Archiver**: Archiver and point-in-time-recovery within `KubeDB` has been enhanced for `MongoDBArchiver`, `MariaDBArchiver`, `MySQLArchiver`, `PostgressArchiver`, `MSSQLArchiver`.
`MSSQLArchiver` -> `MSSQLServerArchiver`

2024-12-20 09:21 UTC, Neaj-Morshad-101 commented on content/post/kubedb-v2024.12.18/index.md
> +Archiver support has been enhanced for `MongoDBArchiver`, `MariaDBArchiver`, `MySQLArchiver`, `PostgressArchiver` and `MSSQLArchiver`. We have replaced the field `spec.walBackup` in spec with `spec.l
MSSQLArchiver -> MSSQLServerArchiver

2024-12-20 09:21 UTC, Neaj-Morshad-101 commented on content/post/kubedb-v2024.12.18/index.md
> +In this Release, we are introducing `Recommendation` support for KubeDB managed Kafka instances. KubeDB ops-manager generates three types of recommendations for Kafka - Version Update Recommendation,
kubedb -> KubeDB

2024-12-23 04:50 UTC, sayedppqq approved these changes
LGTM

2024-12-23 05:03 UTC, AshrafulHaqueToni reviewed
LGTM!

2024-12-23 05:57 UTC, tapojit047 submitted a review, later dismissed
LGTM!

2024-12-23 06:23 UTC, obaydullahmhs approved these changes
LGTM!

2024-12-23 06:38 UTC, raihankhan approved these changes
LGTM 👍🏻

2024-12-23 08:27 UTC, merged