Add backup verification in blog post
appscode/blog pull request #491
Opened 2024-12-31 11:32 UTC by ishtiaqhimel

2025-01-01 05:57 UTC, hmsayem requested changes

2025-01-01 05:57 UTC, hmsayem commented on content/post/stash-2.0/index.md
> +| **Backup Verification:** You can refer a `BackupVerifier` for each repository in a `BackupConfiguration` which contains the configuration for backup verification.  | &#10007; | &#10003;
You can enable automatic verification of backed-up data by using BackupVerifier for each repository specified in a `BackupConfiguration`

2025-01-02 06:45 UTC, anisurrahman75 submitted a review, later dismissed

2025-01-02 06:51 UTC, hmsayem commented on content/post/stash-2.0/index.md
> +| **Backup Verification:** You can enable automatic verification of backed-up data by using `BackupVerifier` for each repository specified in a `BackupConfiguration`. | &#10007; | &#10003;
You can verify the integrity of backed-up data by enabling backup verification using `BackupVerifier` for each repository specified in a `BackupConfiguration`.

2025-01-02 08:45 UTC, hmsayem approved these changes

2025-01-02 09:22 UTC, merged